# -*- coding: utf-8 -*-
"""Diabetes risk scoring

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-xqxo9kVevHQSlWCsf1VBEKDXB53oneD
"""



"""
===============================================================================
DIABETES RISK SCORING SYSTEM
Architecture: 4-Tier Software Architecture
  1. Data Access Layer (Model/Repository)
  2. Business Logic Layer (Service)
  3. Presentation Layer (View)
  4. Orchestration Layer (Controller)
===============================================================================
"""

import math
import statistics
import sys
import time
import unittest
from dataclasses import dataclass
from io import StringIO
from typing import Dict, List, Optional, Tuple

# =============================================================================
# CONFIGURATION & TOGGLE SWITCH
# =============================================================================
# Set to True to execute the 3-Tier Testing Suite (Unit, E2E, Performance).
# Set to False to launch the interactive command-line application.
RUN_TEST_SUITE: bool = False


# =============================================================================
# TIER 1: DATA ACCESS LAYER (THE MODEL & REPOSITORY)
# =============================================================================
@dataclass
class PatientProfile:
    """Represents the raw clinical profile of a patient."""

    patient_id: int
    glucose: float  # Fasting plasma glucose (mg/dL)
    bmi: float  # Body Mass Index (kg/m²)
    age: int  # Age in years
    blood_pressure: float  # Systolic blood pressure (mmHg)


class PatientRepository:
    """Manages data persistence, retrieval, and initial data cleansing."""

    def __init__(self) -> None:
        # Data Mockup: 4 sample patients (Patient 103 intentionally has BMI = 0)
        self._patients: Dict[int, PatientProfile] = {
            101: PatientProfile(
                patient_id=101, glucose=92.0, bmi=22.5, age=32, blood_pressure=115.0
            ),
            102: PatientProfile(
                patient_id=102, glucose=112.0, bmi=27.4, age=51, blood_pressure=128.0
            ),
            103: PatientProfile(
                patient_id=103, glucose=145.0, bmi=0.0, age=68, blood_pressure=142.0
            ),
            104: PatientProfile(
                patient_id=104, glucose=185.0, bmi=34.8, age=71, blood_pressure=155.0
            ),
        }
        # Perform data cleaning upon initialization
        self._cleanse_data()

    def _cleanse_data(self) -> None:
        """Data Cleansing Rule: Automatically replace invalid BMI (0) with the median BMI of valid patients."""
        valid_bmis = [p.bmi for p in self._patients.values() if p.bmi > 0]

        if not valid_bmis:
            default_bmi = 25.0  # Fallback if no valid BMIs exist
        else:
            default_bmi = statistics.median(valid_bmis)

        for patient in self._patients.values():
            if patient.bmi <= 0:
                patient.bmi = round(default_bmi, 1)

    def get_all_ids(self) -> List[int]:
        """Returns a list of all registered patient IDs."""
        return sorted(list(self._patients.keys()))

    def get_by_id(self, patient_id: int) -> Optional[PatientProfile]:
        """Retrieves a patient profile by ID, or None if not found."""
        patient = self._patients.get(patient_id)
        if patient:
            # Return a shallow copy to prevent unintended direct state mutation
            return PatientProfile(
                patient.patient_id,
                patient.glucose,
                patient.bmi,
                patient.age,
                patient.blood_pressure,
            )
        return None

    def update_patient(self, updated_profile: PatientProfile) -> None:
        """Persists updated patient clinical metrics back to data storage."""
        if updated_profile.patient_id in self._patients:
            self._patients[updated_profile.patient_id] = updated_profile


# =============================================================================
# TIER 2: BUSINESS LOGIC LAYER (THE SERVICE)
# =============================================================================
@dataclass
class MetricScore:
    value: float
    range_category: str  # "Low", "Medium", "High"
    points: int


@dataclass
class DiagnosticRiskReport:
    patient_id: int
    glucose_score: MetricScore
    bmi_score: MetricScore
    age_score: MetricScore
    bp_score: MetricScore
    total_score: int
    risk_category: str  # "Low Risk", "Moderate Risk", "High Risk"


class DiabetesRiskService:
    """Encapsulates pure clinical decision rules and scoring logic."""

    @staticmethod
    def score_glucose(glucose: float) -> MetricScore:
        """Clinical Thresholds: Low (<100), Medium (100-125), High (>=126)"""
        if glucose < 100:
            return MetricScore(glucose, "Low", 0)
        elif 100 <= glucose <= 125:
            return MetricScore(glucose, "Medium", 1)
        else:
            return MetricScore(glucose, "High", 2)

    @staticmethod
    def score_bmi(bmi: float) -> MetricScore:
        """Clinical Thresholds: Low (<25.0), Medium (25.0-29.9), High (>=30.0)"""
        if bmi < 25.0:
            return MetricScore(bmi, "Low", 0)
        elif 25.0 <= bmi <= 29.9:
            return MetricScore(bmi, "Medium", 1)
        else:
            return MetricScore(bmi, "High", 2)

    @staticmethod
    def score_age(age: int) -> MetricScore:
        """Clinical Thresholds: Low (<45), Medium (45-64), High (>=65)"""
        if age < 45:
            return MetricScore(float(age), "Low", 0)
        elif 45 <= age <= 64:
            return MetricScore(float(age), "Medium", 1)
        else:
            return MetricScore(float(age), "High", 2)

    @staticmethod
    def score_blood_pressure(bp: float) -> MetricScore:
        """Clinical Thresholds: Low (<120), Medium (120-139), High (>=140)"""
        if bp < 120:
            return MetricScore(bp, "Low", 0)
        elif 120 <= bp <= 139:
            return MetricScore(bp, "Medium", 1)
        else:
            return MetricScore(bp, "High", 2)

    def calculate_risk(self, patient: PatientProfile) -> DiagnosticRiskReport:
        """Aggregates scores across all metrics and evaluates overall risk category."""
        g_score = self.score_glucose(patient.glucose)
        b_score = self.score_bmi(patient.bmi)
        a_score = self.score_age(patient.age)
        p_score = self.score_blood_pressure(patient.blood_pressure)

        total_score = (
            g_score.points + b_score.points + a_score.points + p_score.points
        )

        # Total Risk Categorization Rules: Low (0-2), Moderate (3-5), High (6+)
        if total_score <= 2:
            risk_category = "Low Risk"
        elif 3 <= total_score <= 5:
            risk_category = "Moderate Risk"
        else:
            risk_category = "High Risk"

        return DiagnosticRiskReport(
            patient_id=patient.patient_id,
            glucose_score=g_score,
            bmi_score=b_score,
            age_score=a_score,
            bp_score=p_score,
            total_score=total_score,
            risk_category=risk_category,
        )


# =============================================================================
# TIER 3: PRESENTATION LAYER (THE VIEW)
# =============================================================================
class ConsoleView:
    """Handles CLI formatting, user interactions, and diagnostic output display."""

    @staticmethod
    def show_main_menu() -> str:
        print("\n" + "=" * 50)
        print("    DIABETES RISK ASSESSMENT SYSTEM")
        print("=" * 50)
        print("1. Assess Patient Risk")
        print("2. Exit")
        return input("Select an option (1-2): ").strip()

    @staticmethod
    def display_patient_list(patient_ids: List[int]) -> None:
        ids_str = ", ".join(map(str, patient_ids))
        print(f"\nAvailable Patient IDs: [{ids_str}]")

    @staticmethod
    def prompt_patient_id() -> str:
        return input("Enter Patient ID to assess: ").strip()

    @staticmethod
    def display_patient_profile(patient: PatientProfile) -> None:
        print(f"\n--- Patient Profile [ID: {patient.patient_id}] ---")
        print(f"  • Fasting Glucose : {patient.glucose:.1f} mg/dL")
        print(f"  • BMI             : {patient.bmi:.1f} kg/m²")
        print(f"  • Age             : {patient.age} years")
        print(f"  • Blood Pressure  : {patient.blood_pressure:.1f} mmHg")

    @staticmethod
    def prompt_modify_metrics() -> bool:
        choice = (
            input(
                "\nWould you like to modify any clinical metrics before assessment? (y/N): "
            )
            .strip()
            .lower()
        )
        return choice in ["y", "yes"]

    @staticmethod
    def prompt_metric_update(
        field_name: str, current_value: float, is_int: bool = False
    ) -> float:
        val_str = input(
            f"  Enter new {field_name} (Press Enter to keep [{current_value}]): "
        ).strip()
        if not val_str:
            return current_value
        try:
            val = float(val_str)
            if val < 0:
                print("  [!] Value cannot be negative. Retaining current value.")
                return current_value
            return int(val) if is_int else val
        except ValueError:
            print("  [!] Invalid numeric input. Retaining current value.")
            return current_value

    @staticmethod
    def display_diagnostic_report(report: DiagnosticRiskReport) -> None:
        print("\n" + "─" * 55)
        print(
            f"       DIAGNOSTIC RISK REPORT — PATIENT #{report.patient_id}"
        )
        print("─" * 55)
        print(
            f" Metric             | Value     | Range Score | Points"
        )
        print("─" * 55)
        print(
            f" Fasting Glucose    | {report.glucose_score.value:>6.1f}   | {report.glucose_score.range_category:<11} | {report.glucose_score.points}"
        )
        print(
            f" Body Mass Index    | {report.bmi_score.value:>6.1f}   | {report.bmi_score.range_category:<11} | {report.bmi_score.points}"
        )
        print(
            f" Age                | {report.age_score.value:>6.0f}   | {report.age_score.range_category:<11} | {report.age_score.points}"
        )
        print(
            f" Blood Pressure     | {report.bp_score.value:>6.1f}   | {report.bp_score.range_category:<11} | {report.bp_score.points}"
        )
        print("─" * 55)
        print(f" TOTAL CLINICAL SCORE: {report.total_score}")
        print(f" RISK ASSESSMENT     : [{report.risk_category.upper()}]")
        print("─" * 55)

    @staticmethod
    def display_error(msg: str) -> None:
        print(f"\n[ERROR] {msg}")

    @staticmethod
    def display_message(msg: str) -> None:
        print(f"\n{msg}")


# =============================================================================
# TIER 4: ORCHESTRATION LAYER (THE CONTROLLER)
# =============================================================================
class DiabetesRiskController:
    """Coordinates workflow actions, managing state across Data, Service, and View layers."""

    def __init__(
        self,
        repository: PatientRepository,
        service: DiabetesRiskService,
        view: ConsoleView,
    ) -> None:
        self.repo = repository
        self.service = service
        self.view = view

    def start(self) -> None:
        """Main execution loop (Core Workflows 01 & 02)."""
        while True:
            choice = self.view.show_main_menu()
            if choice == "1":
                self._handle_patient_assessment()
            elif choice == "2":
                self.view.display_message(
                    "Exiting Diabetes Risk Scoring System. Good morning/evening!"
                )
                break
            else:
                self.view.display_error("Invalid selection. Please choose 1 or 2.")

    def _handle_patient_assessment(self) -> None:
        """Core Workflow 01 Implementation."""
        valid_ids = self.repo.get_all_ids()
        self.view.display_patient_list(valid_ids)

        raw_id = self.view.prompt_patient_id()

        # Input Validation: Check numeric and presence
        if not raw_id.isdigit():
            self.view.display_error(
                "Invalid input format. Patient ID must be an integer."
            )
            return

        patient_id = int(raw_id)
        patient = self.repo.get_by_id(patient_id)

        if not patient:
            self.view.display_error(
                f"Patient ID {patient_id} does not exist in records."
            )
            return

        # Display current baseline profile
        self.view.display_patient_profile(patient)

        # Metric update option
        if self.view.prompt_modify_metrics():
            print("\nUpdate Metrics (Press Enter to keep existing value):")
            patient.glucose = self.view.prompt_metric_update(
                "Glucose (mg/dL)", patient.glucose
            )
            patient.bmi = self.view.prompt_metric_update(
                "BMI (kg/m²)", patient.bmi
            )
            patient.age = int(
                self.view.prompt_metric_update(
                    "Age (years)", float(patient.age), is_int=True
                )
            )
            patient.blood_pressure = self.view.prompt_metric_update(
                "Blood Pressure (mmHg)", patient.blood_pressure
            )

            # Persist updated values back to repository
            self.repo.update_patient(patient)

        # Calculate clinical risk score
        report = self.service.calculate_risk(patient)

        # Output diagnostic risk report
        self.view.display_diagnostic_report(report)


# =============================================================================
# 3-TIER TESTING SUITE (UNIT, END-TO-END, PERFORMANCE)
# =============================================================================


# --- Tier A: Unit Tests ---
class TestDataCleansingAndScoring(unittest.TestCase):
    """Verifies data access layer cleansing rules and service layer decision logic."""

    def setUp(self) -> None:
        self.repo = PatientRepository()
        self.service = DiabetesRiskService()

    def test_zero_bmi_cleansing(self) -> None:
        """Ensure BMI of 0 is automatically corrected to median of valid BMIs."""
        # Valid BMIs in mockup: 22.5, 27.4, 34.8 -> Median = 27.4
        patient_103 = self.repo.get_by_id(103)
        self.assertIsNotNone(patient_103)
        self.assertEqual(patient_103.bmi, 27.4)

    def test_glucose_scoring_thresholds(self) -> None:
        self.assertEqual(self.service.score_glucose(85.0).points, 0)
        self.assertEqual(self.service.score_glucose(110.0).points, 1)
        self.assertEqual(self.service.score_glucose(140.0).points, 2)

    def test_risk_category_assignment(self) -> None:
        # Low risk test profile (Total score = 0)
        p_low = PatientProfile(
            patient_id=999, glucose=90.0, bmi=22.0, age=30, blood_pressure=110.0
        )
        report_low = self.service.calculate_risk(p_low)
        self.assertEqual(report_low.total_score, 0)
        self.assertEqual(report_low.risk_category, "Low Risk")

        # Moderate risk test profile (Total score = 4)
        p_mod = PatientProfile(
            patient_id=999, glucose=115.0, bmi=28.0, age=50, blood_pressure=130.0
        )
        report_mod = self.service.calculate_risk(p_mod)
        self.assertEqual(report_mod.total_score, 4)
        self.assertEqual(report_mod.risk_category, "Moderate Risk")

        # High risk test profile (Total score = 8)
        p_high = PatientProfile(
            patient_id=999, glucose=150.0, bmi=35.0, age=70, blood_pressure=150.0
        )
        report_high = self.service.calculate_risk(p_high)
        self.assertEqual(report_high.total_score, 8)
        self.assertEqual(report_high.risk_category, "High Risk")


# --- Tier B: End-to-End (E2E) Tests ---
class TestEndToEndWorkflow(unittest.TestCase):
    """Simulates complete user interaction loops from input to CLI report output."""

    def test_e2e_successful_patient_assessment(self) -> None:
        repo = PatientRepository()
        service = DiabetesRiskService()
        view = ConsoleView()
        controller = DiabetesRiskController(repo, service, view)

        # Mock user input sequence:
        # 1 -> Choose "Assess Patient Risk"
        # 101 -> Select Patient ID 101
        # n -> Do not modify metrics
        # 2 -> Choose "Exit"
        simulated_inputs = ["1", "101", "n", "2"]

        sys.stdin = StringIO("\n".join(simulated_inputs))
        captured_output = StringIO()
        sys.stdout = captured_output

        try:
            controller.start()
        finally:
            sys.stdin = sys.__stdin__
            sys.stdout = sys.__stdout__

        output = captured_output.getvalue()
        self.assertIn("DIAGNOSTIC RISK REPORT — PATIENT #101", output)
        self.assertIn("TOTAL CLINICAL SCORE: 0", output)
        self.assertIn("[LOW RISK]", output)

    def test_e2e_invalid_patient_id_handling(self) -> None:
        repo = PatientRepository()
        service = DiabetesRiskService()
        view = ConsoleView()
        controller = DiabetesRiskController(repo, service, view)

        # Mock inputs: 1 (Assess), 'abc' (invalid ID), 2 (Exit)
        simulated_inputs = ["1", "abc", "2"]

        sys.stdin = StringIO("\n".join(simulated_inputs))
        captured_output = StringIO()
        sys.stdout = captured_output

        try:
            controller.start()
        finally:
            sys.stdin = sys.__stdin__
            sys.stdout = sys.__stdout__

        output = captured_output.getvalue()
        self.assertIn("[ERROR] Invalid input format", output)


# --- Tier C: Performance Benchmark ---
def run_performance_benchmark(iterations: int = 100_000) -> None:
    """Measures and logs processing speed for high-volume batch risk calculations."""
    service = DiabetesRiskService()
    patient = PatientProfile(
        patient_id=888, glucose=130.0, bmi=28.5, age=55, blood_pressure=135.0
    )

    print(
        f"\n[PERFORMANCE] Executing speed benchmark ({iterations:,} evaluations)..."
    )

    start_time = time.perf_counter()
    for _ in range(iterations):
        _ = service.calculate_risk(patient)
    end_time = time.perf_counter()

    elapsed = end_time - start_time
    ops_per_sec = iterations / elapsed if elapsed > 0 else float("inf")

    print(f"  • Total Elapsed Time : {elapsed:.4f} seconds")
    print(f"  • Throughput Rate    : {ops_per_sec:,.0f} evaluations/sec")
    print(
        f"  • Average Latency    : {(elapsed / iterations) * 1e6:.3f} microseconds/op"
    )


def execute_full_test_suite() -> None:
    """Master orchestrator for the 3-Tier Testing Suite."""
    print("\n" + "=" * 60)
    print("      RUNNING 3-TIER AUTOMATED TESTING SUITE")
    print("=" * 60)

    # 1. Unit Tests & 2. E2E Tests via unittest framework
    print("\n[TIER 1 & 2] Executing Unit and End-to-End Test Suites...")
    suite = unittest.TestSuite()
    suite.addTest(unittest.makeSuite(TestDataCleansingAndScoring))
    suite.addTest(unittest.makeSuite(TestEndToEndWorkflow))

    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)

    # 3. Performance Benchmark
    print("\n[TIER 3] Executing Performance Benchmark Suite...")
    run_performance_benchmark()

    print("\n" + "=" * 60)
    if result.wasSuccessful():
        print("  SUCCESS: ALL 3 TIERS PASSED PERFECTLY!")
    else:
        print("  FAILURE: SOME TEST CASES FAILED.")
    print("=" * 60 + "\n")


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================
if __name__ == "__main__":
    if RUN_TEST_SUITE:
        execute_full_test_suite()
    else:
        # Dependency Injection / App Initialization
        repository = PatientRepository()
        service = DiabetesRiskService()
        view = ConsoleView()

        controller = DiabetesRiskController(repository, service, view)
        controller.start()