# -*- coding: utf-8 -*-
"""Diabetes risk scoring

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-xqxo9kVevHQSlWCsf1VBEKDXB53oneD
"""



"""
===============================================================================
DIABETES RISK SCORING SYSTEM
Architecture: 4-Tier Software Architecture
  1. Data Access Layer (Model/Repository)
  2. Business Logic Layer (Service)
  3. Presentation Layer (View)
  4. Orchestration Layer (Controller)
===============================================================================
"""

import math
import statistics
import sys
import time
import unittest
from dataclasses import dataclass
from io import StringIO
from typing import Dict, List, Optional, Tuple

# =============================================================================
# CONFIGURATION & TOGGLE SWITCH
# =============================================================================
# Set to True to execute the 3-Tier Testing Suite (Unit, E2E, Performance).
# Set to False to launch the interactive command-line application.
RUN_TEST_SUITE: bool = False


# =============================================================================
# TIER 1: DATA ACCESS LAYER (THE MODEL & REPOSITORY)
# =============================================================================
@dataclass
class PatientProfile:
    """Represents the raw clinical profile of a patient."""

    patient_id: int
    glucose: float  # Fasting plasma glucose (mg/dL)
    bmi: float  # Body Mass Index (kg/m²)
    age: int  # Age in years
    blood_pressure: float  # Systolic blood pressure (mmHg)


class PatientRepository:
    """Manages data persistence, retrieval, and initial data cleansing."""

    def __init__(self) -> None:
        # Data Mockup: 4 sample patients (Patient 103 intentionally has BMI = 0)
        self._patients: Dict[int, PatientProfile] = {
            101: PatientProfile(
                patient_id=101, glucose=92.0, bmi=22.5, age=32, blood_pressure=115.0
            ),
            102: PatientProfile(
                patient_id=102, glucose=112.0, bmi=27.4, age=51, blood_pressure=128.0
            ),
            103: PatientProfile(
                patient_id=103, glucose=145.0, bmi=0.0, age=68, blood_pressure=142.0
            ),
            104: PatientProfile(
                patient_id=104, glucose=185.0, bmi=34.8, age=71, blood_pressure=155.0
            ),
        }
        # Perform data cleaning upon initialization
        self._cleanse_data()

    def _cleanse_data(self) -> None:
        """Data Cleansing Rule: Automatically replace invalid BMI (0) with the median BMI of valid patients."""
        valid_bmis = [p.bmi for p in self._patients.values() if p.bmi > 0]

        if not valid_bmis:
            default_bmi = 25.0  # Fallback if no valid BMIs exist
        else:
            default_bmi = statistics.median(valid_bmis)

        for patient in self._patients.values():
            if patient.bmi <= 0:
                patient.bmi = round(default_bmi, 1)

    def get_all_ids(self) -> List[int]:
        """Returns a list of all registered patient IDs."""
        return sorted(list(self._patients.keys()))

    def get_by_id(self, patient_id: int) -> Optional[PatientProfile]:
        """Retrieves a patient profile by ID, or None if not found."""
        patient = self._patients.get(patient_id)
        if patient:
            # Return a shallow copy to prevent unintended direct state mutation
            return PatientProfile(
                patient.patient_id,
                patient.glucose,
                patient.bmi,
                patient.age,
                patient.blood_pressure,
            )
        return None

    def update_patient(self, updated_profile: PatientProfile) -> None:
        """Persists updated patient clinical metrics back to data storage."""
        if updated_profile.patient_id in self._patients:
            self._patients[updated_profile.patient_id] = updated_profile


# =============================================================================
# TIER 2: BUSINESS LOGIC LAYER (THE SERVICE)
# =============================================================================
@dataclass
class MetricScore:
    value: float
    range_category: str  # "Low", "Medium", "High"
    points: int


@dataclass
class DiagnosticRiskReport:
    patient_id: int
    glucose_score: MetricScore
    bmi_score: MetricScore
    age_score: MetricScore
    bp_score: MetricScore
    total_score: int
    risk_category: str  # "Low Risk", "Moderate Risk", "High Risk"


class DiabetesRiskService:
    """Encapsulates pure clinical decision rules and scoring logic."""

    @staticmethod
    def score_glucose(glucose: float) -> MetricScore:
        """Clinical Thresholds: Low (<100), Medium (100-125), High (>=126)"""
        if glucose < 100:
            return MetricScore(glucose, "Low", 0)
        elif 100 <= glucose <= 125:
            return MetricScore(glucose, "Medium", 1)
        else:
            return MetricScore(glucose, "High", 2)

    @staticmethod
    def score_bmi(bmi: float) -> MetricScore:
        """Clinical Thresholds: Low (<25.0), Medium (25.0-29.9), High (>=30.0)"""
        if bmi < 25.0:
            return MetricScore(bmi, "Low", 0)
        elif 25.0 <= bmi <= 29.9:
            return MetricScore(bmi, "Medium", 1)
        else:
            return MetricScore(bmi, "High", 2)

    @staticmethod
    def score_age(age: int) -> MetricScore:
        """Clinical Thresholds: Low (<45), Medium (45-64), High (>=65)"""
        if age < 45:
            return MetricScore(float(age), "Low", 0)
        elif 45 <= age <= 64:
            return MetricScore(float(age), "Medium", 1)
        else:
            return MetricScore(float(age), "High", 2)

    @staticmethod
    def score_blood_pressure(bp: float) -> MetricScore:
        """Clinical Thresholds: Low (<120), Medium (120-139), High (>=140)"""
        if bp < 120:
            return MetricScore(bp, "Low", 0)
        elif 120 <= bp <= 139:
            return MetricScore(bp, "Medium", 1)
        else:
            return MetricScore(bp, "High", 2)

    def calculate_risk(self, patient: PatientProfile) -> DiagnosticRiskReport:
        """Aggregates scores across all metrics and evaluates overall risk category."""
        g_score = self.score_glucose(patient.glucose)
        b_score = self.score_bmi(patient.bmi)
        a_score = self.score_age(patient.age)
        p_score = self.score_blood_pressure(patient.blood_pressure)

        total_score = (
            g_score.points + b_score.points + a_score.points + p_score.points
        )

        # Total Risk Categorization Rules: Low (0-2), Moderate (3-5), High (6+)
        if total_score <= 2:
            risk_category = "Low Risk"
        elif 3 <= total_score <= 5:
            risk_category = "Moderate Risk"
        else:
            risk_category = "High Risk"

        return DiagnosticRiskReport(
            patient_id=patient.patient_id,
            glucose_score=g_score,
            bmi_score=b_score,
            age_score=a_score,
            bp_score=p_score,
            total_score=total_score,
            risk_category=risk_category,
        )


# =============================================================================
import streamlit as st

# =============================================================================
# TIER 3 & 4: STREAMLIT PRESENTATION & ORCHESTRATION LAYER
# =============================================================================


def run_streamlit_app(
    repository: PatientRepository, service: DiabetesRiskService
):
    st.set_page_config(
        page_title="Diabetes Risk Scoring System", page_icon="🩺", layout="wide"
    )

    st.title("🩺 Diabetes Risk Assessment System")
    st.markdown("---")

    # Sidebar: Patient Selection
    st.sidebar.header("Patient Selection")
    patient_ids = repository.get_all_ids()

    selected_id = st.sidebar.selectbox(
        "Select Patient ID",
        options=patient_ids,
        index=0 if patient_ids else None,
    )

    if selected_id:
        # Retrieve baseline profile from Repository
        patient = repository.get_by_id(selected_id)

        if patient:
            st.subheader(f"Patient Profile — ID: #{patient.patient_id}")

            # Form layout for clinical metrics input
            with st.form(key="patient_metrics_form"):
                col1, col2 = st.columns(2)

                with col1:
                    glucose = st.number_input(
                        "Fasting Glucose (mg/dL)",
                        min_value=0.0,
                        value=float(patient.glucose),
                        step=0.1,
                    )
                    bmi = st.number_input(
                        "Body Mass Index - BMI (kg/m²)",
                        min_value=0.0,
                        value=float(patient.bmi),
                        step=0.1,
                    )

                with col2:
                    age = st.number_input(
                        "Age (years)",
                        min_value=0,
                        value=int(patient.age),
                        step=1,
                    )
                    bp = st.number_input(
                        "Blood Pressure (mmHg)",
                        min_value=0.0,
                        value=float(patient.blood_pressure),
                        step=0.1,
                    )

                submit_button = st.form_submit_button(
                    label="Assess Diabetes Risk", type="primary"
                )

            # Execution logic upon form submission
            if submit_button:
                # 1. Update patient profile in repository
                updated_patient = PatientProfile(
                    patient_id=selected_id,
                    glucose=glucose,
                    bmi=bmi,
                    age=age,
                    blood_pressure=bp,
                )
                repository.update_patient(updated_patient)

                # 2. Calculate risk report via Service Layer
                report = service.calculate_risk(updated_patient)

                # 3. Display Results
                st.markdown("---")
                st.subheader(
                    f"📊 Diagnostic Risk Report — Patient #{report.patient_id}"
                )

                # Table of metric scores
                report_data = [
                    {
                        "Metric": "Fasting Glucose",
                        "Value": f"{report.glucose_score.value:.1f} mg/dL",
                        "Range Category": report.glucose_score.range_category,
                        "Points": report.glucose_score.points,
                    },
                    {
                        "Metric": "Body Mass Index (BMI)",
                        "Value": f"{report.bmi_score.value:.1f} kg/m²",
                        "Range Category": report.bmi_score.range_category,
                        "Points": report.bmi_score.points,
                    },
                    {
                        "Metric": "Age",
                        "Value": f"{report.age_score.value:.0f} years",
                        "Range Category": report.age_score.range_category,
                        "Points": report.age_score.points,
                    },
                    {
                        "Metric": "Blood Pressure",
                        "Value": f"{report.bp_score.value:.1f} mmHg",
                        "Range Category": report.bp_score.range_category,
                        "Points": report.bp_score.points,
                    },
                ]

                st.table(report_data)

                # Summary Metrics Banner
                res_col1, res_col2 = st.columns(2)

                with res_col1:
                    st.metric(
                        label="Total Clinical Score", value=report.total_score
                    )

                with res_col2:
                    # Highlight status based on risk level
                    risk_cat = report.risk_category.upper()
                    if report.risk_category == "Low Risk":
                        st.success(f"Risk Assessment: **{risk_cat}**")
                    elif report.risk_category == "Moderate Risk":
                        st.warning(f"Risk Assessment: **{risk_cat}**")
                    else:
                        st.error(f"Risk Assessment: **{risk_cat}**")


# =============================================================================
# STREAMLIT ENTRY POINT
# =============================================================================
if __name__ == "__main__":
    # Maintain state across Streamlit re-runs using session_state
    if "repository" not in st.session_state:
        st.session_state.repository = PatientRepository()

    if "service" not in st.session_state:
        st.session_state.service = DiabetesRiskService()

    run_streamlit_app(st.session_state.repository, st.session_state.service)

# =============================================================================
# 3-TIER TESTING SUITE (UNIT, END-TO-END, PERFORMANCE)
# =============================================================================


# --- Tier A: Unit Tests ---
class TestDataCleansingAndScoring(unittest.TestCase):
    """Verifies data access layer cleansing rules and service layer decision logic."""

    def setUp(self) -> None:
        self.repo = PatientRepository()
        self.service = DiabetesRiskService()

    def test_zero_bmi_cleansing(self) -> None:
        """Ensure BMI of 0 is automatically corrected to median of valid BMIs."""
        # Valid BMIs in mockup: 22.5, 27.4, 34.8 -> Median = 27.4
        patient_103 = self.repo.get_by_id(103)
        self.assertIsNotNone(patient_103)
        self.assertEqual(patient_103.bmi, 27.4)

    def test_glucose_scoring_thresholds(self) -> None:
        self.assertEqual(self.service.score_glucose(85.0).points, 0)
        self.assertEqual(self.service.score_glucose(110.0).points, 1)
        self.assertEqual(self.service.score_glucose(140.0).points, 2)

    def test_risk_category_assignment(self) -> None:
        # Low risk test profile (Total score = 0)
        p_low = PatientProfile(
            patient_id=999, glucose=90.0, bmi=22.0, age=30, blood_pressure=110.0
        )
        report_low = self.service.calculate_risk(p_low)
        self.assertEqual(report_low.total_score, 0)
        self.assertEqual(report_low.risk_category, "Low Risk")

        # Moderate risk test profile (Total score = 4)
        p_mod = PatientProfile(
            patient_id=999, glucose=115.0, bmi=28.0, age=50, blood_pressure=130.0
        )
        report_mod = self.service.calculate_risk(p_mod)
        self.assertEqual(report_mod.total_score, 4)
        self.assertEqual(report_mod.risk_category, "Moderate Risk")

        # High risk test profile (Total score = 8)
        p_high = PatientProfile(
            patient_id=999, glucose=150.0, bmi=35.0, age=70, blood_pressure=150.0
        )
        report_high = self.service.calculate_risk(p_high)
        self.assertEqual(report_high.total_score, 8)
        self.assertEqual(report_high.risk_category, "High Risk")


# --- Tier B: End-to-End (E2E) Tests ---
class TestEndToEndWorkflow(unittest.TestCase):
    """Simulates complete user interaction loops from input to CLI report output."""

    def test_e2e_successful_patient_assessment(self) -> None:
        repo = PatientRepository()
        service = DiabetesRiskService()
        view = ConsoleView()
        controller = DiabetesRiskController(repo, service, view)

        # Mock user input sequence:
        # 1 -> Choose "Assess Patient Risk"
        # 101 -> Select Patient ID 101
        # n -> Do not modify metrics
        # 2 -> Choose "Exit"
        simulated_inputs = ["1", "101", "n", "2"]

        sys.stdin = StringIO("\n".join(simulated_inputs))
        captured_output = StringIO()
        sys.stdout = captured_output

        try:
            controller.start()
        finally:
            sys.stdin = sys.__stdin__
            sys.stdout = sys.__stdout__

        output = captured_output.getvalue()
        self.assertIn("DIAGNOSTIC RISK REPORT — PATIENT #101", output)
        self.assertIn("TOTAL CLINICAL SCORE: 0", output)
        self.assertIn("[LOW RISK]", output)

    def test_e2e_invalid_patient_id_handling(self) -> None:
        repo = PatientRepository()
        service = DiabetesRiskService()
        view = ConsoleView()
        controller = DiabetesRiskController(repo, service, view)

        # Mock inputs: 1 (Assess), 'abc' (invalid ID), 2 (Exit)
        simulated_inputs = ["1", "abc", "2"]

        sys.stdin = StringIO("\n".join(simulated_inputs))
        captured_output = StringIO()
        sys.stdout = captured_output

        try:
            controller.start()
        finally:
            sys.stdin = sys.__stdin__
            sys.stdout = sys.__stdout__

        output = captured_output.getvalue()
        self.assertIn("[ERROR] Invalid input format", output)


# --- Tier C: Performance Benchmark ---
def run_performance_benchmark(iterations: int = 100_000) -> None:
    """Measures and logs processing speed for high-volume batch risk calculations."""
    service = DiabetesRiskService()
    patient = PatientProfile(
        patient_id=888, glucose=130.0, bmi=28.5, age=55, blood_pressure=135.0
    )

    print(
        f"\n[PERFORMANCE] Executing speed benchmark ({iterations:,} evaluations)..."
    )

    start_time = time.perf_counter()
    for _ in range(iterations):
        _ = service.calculate_risk(patient)
    end_time = time.perf_counter()

    elapsed = end_time - start_time
    ops_per_sec = iterations / elapsed if elapsed > 0 else float("inf")

    print(f"  • Total Elapsed Time : {elapsed:.4f} seconds")
    print(f"  • Throughput Rate    : {ops_per_sec:,.0f} evaluations/sec")
    print(
        f"  • Average Latency    : {(elapsed / iterations) * 1e6:.3f} microseconds/op"
    )


def execute_full_test_suite() -> None:
    """Master orchestrator for the 3-Tier Testing Suite."""
    print("\n" + "=" * 60)
    print("      RUNNING 3-TIER AUTOMATED TESTING SUITE")
    print("=" * 60)

    # 1. Unit Tests & 2. E2E Tests via unittest framework
    print("\n[TIER 1 & 2] Executing Unit and End-to-End Test Suites...")
    suite = unittest.TestSuite()
    suite.addTest(unittest.makeSuite(TestDataCleansingAndScoring))
    suite.addTest(unittest.makeSuite(TestEndToEndWorkflow))

    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)

    # 3. Performance Benchmark
    print("\n[TIER 3] Executing Performance Benchmark Suite...")
    run_performance_benchmark()

    print("\n" + "=" * 60)
    if result.wasSuccessful():
        print("  SUCCESS: ALL 3 TIERS PASSED PERFECTLY!")
    else:
        print("  FAILURE: SOME TEST CASES FAILED.")
    print("=" * 60 + "\n")


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================
if __name__ == "__main__":
    if RUN_TEST_SUITE:
        execute_full_test_suite()
    else:
        # Dependency Injection / App Initialization
        repository = PatientRepository()
        service = DiabetesRiskService()
        view = ConsoleView()

        controller = DiabetesRiskController(repository, service, view)
        controller.start()
